// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIQZkiUf7c2lG8BJ4xtf_ZcFOqYShNTA',
    appId: '1:146765666627:web:a01b03924d61d8582977f6',
    messagingSenderId: '146765666627',
    projectId: 'todo-list-2b4e9',
    authDomain: 'todo-list-2b4e9.firebaseapp.com',
    storageBucket: 'todo-list-2b4e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiZchYi_ybEv6g7o-iIlxVPJMB4nNz8Xs',
    appId: '1:146765666627:android:c00aef1bc328800d2977f6',
    messagingSenderId: '146765666627',
    projectId: 'todo-list-2b4e9',
    storageBucket: 'todo-list-2b4e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqMxbqyXI_trgQfKJPvhw8VmqaEVnFSsY',
    appId: '1:146765666627:ios:d2e4350e7f9c261a2977f6',
    messagingSenderId: '146765666627',
    projectId: 'todo-list-2b4e9',
    storageBucket: 'todo-list-2b4e9.appspot.com',
    iosBundleId: 'com.example.ch11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqMxbqyXI_trgQfKJPvhw8VmqaEVnFSsY',
    appId: '1:146765666627:ios:07fe4824502ab1e02977f6',
    messagingSenderId: '146765666627',
    projectId: 'todo-list-2b4e9',
    storageBucket: 'todo-list-2b4e9.appspot.com',
    iosBundleId: 'com.example.ch11.RunnerTests',
  );
}
